### ISSUE TITLE
Possible to make a variant for PF2E?

### ISSUE THREAD

**Issue by Rayquaza1090** [Halftonex/npc-generator-gpt#10]
### Description

Hello,

I wanted to say I am extremely impressed with the concept behind the module. Were I to ever run 5E again, I would use this in a heartbeat! My group and I are running Pathfinder Second Edition, and I was just curious if you ever had a plan to ever try to make a version for Pathfinder 2e? Thanks for reading.

**Comment by Halftonex** [comment]
Added to the to-do list. Keep in mind, though, that it will take some time as I'm not familiar with pf2e, neither its rules nor system. Additionally, I'm currently developing an HUD based on Baldur's Gate 3.
