### ISSUE TITLE
Error using API Key

### ISSUE THREAD

**Issue by Mesk62** [Halftonex/npc-generator-gpt#2]
Thanks for adding that Halftonex!

Just tried and getting the following:
![image](https://github.com/Halftonex/npc-generator-gpt/assets/43838083/6ce0dfb9-c575-4945-ad42-a90e8a7a113e)

**Comment by Halftonex** [comment]
does it occur every time or was it just a single case? also would be appreciated if you can

**Comment by Halftonex** [comment]
does the error occur everytime? what preferences did you put on creation?

**Comment by Mesk62** [comment]
Haven't completed one yet.  Have tried about 5 times with different preferences, including all random.  Let me try generating a new api key.

**Comment by Moltenmore** [comment]
Hi there, i'm also having this same problem. Tried new keys, new preferences and stull getting the error. Any luck on your side halftonex?

**Comment by Halftonex** [comment]
thanks for the feedback, im gonna have some tests tomorrow and i'll fix it asap.

**Comment by Moltenmore** [comment]
The idea is awesome and from the looks of it this will save me so much time, please don't rush yourself with it my dude <3

**Comment by franckflo** [comment]
FYI I also get that error using my own API Key. I used the default settings that came with your module. Thanks for looking into it and for sharing that cool module with the community !

**Comment by Halftonex** [comment]
Should be fixed

**Comment by franckflo** [comment]
I confirm it worked for me. Thanks !
