### ISSUE TITLE
[FEAT]: extending this feature set to existing actors, including monsters.

### ISSUE THREAD

**Issue by franckflo** [Halftonex/npc-generator-gpt#3]
Hi !

Maybe an idea for a similar module or an extension to this one: the ability to work from an existing actor token and generate AI information about it and maybe upscale/downscale it. I'm thinking about something similar to this by from within Foundry: https://cros.land/ai-powered-dnd-5e-monster-statblock-generator/

**Comment by Mesk62** [comment]
the cros.land generator is pretty cool.   That's a great idea for down the road.  This module could totally be a beautiful solution for instantly generating actors on the fly and moving the story forward, or letting the players go totally off on a tangent.

**Comment by franckflo** [comment]
Indeed. I also imagine it could also be a nice way to "reinvent" a classic monster to make it feel original again;  or maybe beef it up or down to adapt it to a group's level. Food for thought :).

**Comment by Halftonex** [comment]
Thanks francflo for your support, truly appreciated. This sounds really good, added to the todo list!
