### ISSUE TITLE
[FEAT]: Spells and Equipment added to inventory.  

### ISSUE THREAD

**Issue by Mesk62** [Halftonex/npc-generator-gpt#4]
I know Halftone has already said this is in the roadmap, but just adding for tracking here --

Can't wait to have this interact with spells/items etc and auto populate my character sheet with these and class levels if applicable.

Currently, just generated a great little evil bard (was just a totally random generation) so I equipped spells and items it generated for me and intend to use him as a bar-brawl bait next session.  Great stuff for bringing me ideas!  

Thanks again Halftonex.

**Comment by Halftonex** [comment]
Thanks mesk for your support, truly appreciated. This sounds really good, added to the todo list!

**Comment by Mesk62** [comment]
You're right -- Standard Statblocks don't have classes.  Now where's the Ko-fi?

**Comment by Halftonex** [comment]
Do you mean my Ko-fi page? There's really no need man for real, feedback is more than enough and I thank you again for the suggestions you've given me. But if you really want to, surely appreciated, you can find it [here](https://ko-fi.com/halftone).
