### ISSUE TITLE
[FEAT]: Gear added to the generation tool 

### ISSUE THREAD

**Issue by valcoren** [Halftonex/npc-generator-gpt#5]
### Description

Would like to see this generate gear, weapons, armor, and coins into the NPC's inventory.

**Comment by Halftonex** [comment]
Hi @valcoren, thank you for submitting a feature request. By any chance, is what you're referring to in the request the same as what's discussed [here](https://github.com/Halftonex/npc-generator-gpt/issues/4)?

**Comment by valcoren** [comment]
> Hi @valcoren, thank you for submitting a feature request. By any chance, is what you're referring to in the request the same as what's discussed [here](https://github.com/Halftonex/npc-generator-gpt/issues/4)?

It is, I noticed it was already out there after making the submissions. Feel free to disregard it as you are already on it. Thanks for responding to the request.  I currently use Chatgpt to generate all my NPC's I have a prompt that will build Stats, Backstory, Weapons, Armor, Gear, and Lootables. currently, it's a manual process to have to transfer that from Chatgpt to an NPCsheet in Foundry. I would love to have it automated. It seems based on this module you are already on this path.
