### ISSUE TITLE
[BUG]: Create NPC nothing happens

### ISSUE THREAD

**Issue by CasualTerror** [Halftonex/npc-generator-gpt#6]
### Bug Description

Whenever I click the Create NPC button it briefly turns green and says connecting but nothing happens. 
![image](https://github.com/Halftonex/npc-generator-gpt/assets/32625656/585525be-2ca5-4096-82cc-ab90228a76a2)

### Steps To Reproduce

1. Click Create NPC

### Foundry Version

v11.308

**Comment by Halftonex** [comment]
hey there @CasualTerror, the free API seems to have been offline for quite some time now. In fact, I'm thinking of removing it in the next update and just leaving the OpenAI one.
If you want to try it, go to [https://platform.openai.com/account/api-keys](https://platform.openai.com/account/api-keys) and create a private key to insert in the Foundry module settings. Keep in mind that the OpenAI API is not free (you will get free credit upon signing up), although it is very affordable.
