### ISSUE TITLE
[BUG]: Error: This is not a registered game setting [Detected 1 package: npc-generator-gpt]

### ISSUE THREAD

**Issue by tap90** [Halftonex/npc-generator-gpt#7]
### Bug Description

After successfully installing the module, I go to the actor tab, click on 'generate NPC', and select everything I need from the various dropdown menus. But when I press 'Create NPC', nothing happens.

The error mentioned in the title appears in the console.

When I go to 'Configure Settings', there is no reference to this plugin.

### Steps To Reproduce

1- Install the module.
2 - Go to the actor tab.
3 - Click on 'generate NPC'.
4 - Select options from dropdown menus.
5 - Press 'Create NPC' - no response.
6 - Notice error in console.
7 - Go to 'Configure Settings' - no plugin reference.

### Foundry Version

11 Stable 313

### Additional Information

DnD 5e Fifth edition system version 2.3.1

**Comment by Halftonex** [comment]
> The error mentioned in the title appears in the console.

Can you provide a screenshot of the error you get from the console (F12)? It would be very helpful.

> When I go to 'Configure Settings', there is no reference to this plugin.

Can you try to run a world with just my module enabled and check if it is still no reference?

**Comment by tap90** [comment]
![debug-1](https://github.com/Halftonex/npc-generator-gpt/assets/13405068/ce21d2fc-00f8-49e7-bf7c-b955b6eae16c)

This is the error.

![debug-2](https://github.com/Halftonex/npc-generator-gpt/assets/13405068/2c4d1924-e099-4117-bd98-4d36a8c526bc)

This appears to be the line of code that goes wrong.

So I have forced this one in console and the result is as expected.

![debug-3](https://github.com/Halftonex/npc-generator-gpt/assets/13405068/d435d4f7-e4f3-482a-b5e4-345fe4bd3ef3)

It appears as if npc-generator-gtp has not been loaded in game.settings.

If I create a new world works like a charm so probably is a conflict problem?

**Comment by Halftonex** [comment]
> If I create a new world works like a charm so probably is a conflict problem?

yea, definitely. If you want, hit me on discord so we can figure that out
