### ISSUE TITLE
[BUG]: "Request Denied"

### ISSUE THREAD

**Issue by Stormthirst** [Halftonex/npc-generator-gpt#8]
### Bug Description

I'm always getting "request denied: Wait a few seconds and try again"
I have generated an API key, and entered it into the appropriate box.

The console error however says:
```
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
```

Followed by:
`Error: 429 | Message: You exceeded your current quota, please check your plan and billing details.
`

Does this only work on paid-for-subscriptions?

### Steps To Reproduce

Followed procedure described here

### Foundry Version

11.314 and 11.313

**Comment by Halftonex** [comment]
You can find a cost estimate of the API in the updated readme of the module. Additionally, with the latest version of the module, you can check the cost of each call from the logs in the console.
